### ISSUE TITLE
[리뷰페이지/가게조회] 리뷰 작성 위한 가게 조회

### ISSUE THREAD

**Issue by danbom** [Daltokki-develop/cakestation-fe#80]
### 작업 한 줄 요약
- 리뷰 작성 위한 가게 조회
<br/>

### 상세 작업 내용  
- [x] 키워드로 가게 조회

**Comment by danbom** [comment]
찾으시는 가게가 없으신가요? 가 있어야하려나??

**Comment by danbom** [comment]
지금 상태 :
빈 값 검색 시 전체 가게 조회
키워드 검색 시 키워드로 가게 조회

**Comment by danbom** [comment]
처음 들어왔을 때 전체 가게 조회 상태

**Comment by danbom** [comment]
아이템카드 컴포넌트 심플 카드 부분 삭제

**Comment by danbom** [comment]
가로 길이에 세로 길이 맞추는 법!
```css
&:after {
    content: '';
    display: block;
    padding-bottom: 100%;
}
```
